-- MySQL Script generated by MySQL Workbench
-- Fri Jul 12 22:26:25 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_codigo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_codigo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_codigo` DEFAULT CHARACTER SET utf8 ;
USE `db_codigo` ;

-- -----------------------------------------------------
-- Table `db_codigo`.`DATOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_codigo`.`DATOS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `RUC` VARCHAR(45) NOT NULL,
  `FECHA` VARCHAR(45) NOT NULL,
  `CLIENTE` VARCHAR(45) NOT NULL,
  `DIRECCIÓN` VARCHAR(210) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_codigo`.`DESCRIPCIÓN_de_la_Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_codigo`.`DESCRIPCIÓN_de_la_Factura` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` VARCHAR(45) NOT NULL,
  `CANTIDAD` INT NOT NULL,
  `CODIGO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_codigo`.`COSTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_codigo`.`COSTO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `VALOR UNITARIO` INT NOT NULL,
  `IGV` INT NOT NULL,
  `TOTAL` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_codigo`.`MODULO_GENERAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_codigo`.`MODULO_GENERAL` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `DATOS_id` INT NOT NULL,
  `DESCRIPCIÓN_de_la_Factura_id` INT NOT NULL,
  `COSTO_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_MODULO_GENERAL_DATOS_idx` (`DATOS_id` ASC) VISIBLE,
  INDEX `fk_MODULO_GENERAL_DESCRIPCIÓN_de_la_Factura1_idx` (`DESCRIPCIÓN_de_la_Factura_id` ASC) VISIBLE,
  INDEX `fk_MODULO_GENERAL_COSTO1_idx` (`COSTO_id` ASC) VISIBLE,
  CONSTRAINT `fk_MODULO_GENERAL_DATOS`
    FOREIGN KEY (`DATOS_id`)
    REFERENCES `db_codigo`.`DATOS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MODULO_GENERAL_DESCRIPCIÓN_de_la_Factura1`
    FOREIGN KEY (`DESCRIPCIÓN_de_la_Factura_id`)
    REFERENCES `db_codigo`.`DESCRIPCIÓN_de_la_Factura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MODULO_GENERAL_COSTO1`
    FOREIGN KEY (`COSTO_id`)
    REFERENCES `db_codigo`.`COSTO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
