-- MySQL Script generated by MySQL Workbench
-- Sun Jul 14 18:23:11 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema EJECUCION_DE_ORDEN_DE_ART
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema EJECUCION_DE_ORDEN_DE_ART
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EJECUCION_DE_ORDEN_DE_ART` DEFAULT CHARACTER SET utf8 ;
USE `EJECUCION_DE_ORDEN_DE_ART` ;

-- -----------------------------------------------------
-- Table `EJECUCION_DE_ORDEN_DE_ART`.`info_principal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EJECUCION_DE_ORDEN_DE_ART`.`info_principal` (
  `fecha` DATETIME NOT NULL,
  `periodo_contable` VARCHAR(45) NOT NULL,
  `fecha_de_entrega` DATETIME NOT NULL,
  `cliente` VARCHAR(200) NOT NULL,
  `PE_UBICACION_PARA_SERIE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PE_UBICACION_PARA_SERIE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EJECUCION_DE_ORDEN_DE_ART`.`datos_de_la_guia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EJECUCION_DE_ORDEN_DE_ART`.`datos_de_la_guia` (
  `PE_tipo_de_doc` VARCHAR(45) NOT NULL,
  `PE_SERIE` VARCHAR(10) NOT NULL,
  UNIQUE INDEX `PE_tipo_de_doc_UNIQUE` (`PE_tipo_de_doc` ASC) VISIBLE,
  UNIQUE INDEX `PE_SERIE_UNIQUE` (`PE_SERIE` ASC) VISIBLE,
  PRIMARY KEY (`PE_SERIE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EJECUCION_DE_ORDEN_DE_ART`.`Transportista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EJECUCION_DE_ORDEN_DE_ART`.`Transportista` (
  `PE_DELIVERY_INFORMATION` INT NOT NULL,
  `PE_NOM_DE EMP_TRANSPORTE` VARCHAR(45) NOT NULL,
  `PE_RUC_VENDOR` VARCHAR(11) NOT NULL,
  `PE_DOC_DEL_CONDUCTOR` VARCHAR(45) NOT NULL,
  `PE_SERIE` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`PE_SERIE`),
  CONSTRAINT `fk_Transportista_datos_de_la_guia1`
    FOREIGN KEY (`PE_SERIE`)
    REFERENCES `EJECUCION_DE_ORDEN_DE_ART`.`datos_de_la_guia` (`PE_SERIE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EJECUCION_DE_ORDEN_DE_ART`.`DATOS_DEL_VEHICULO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EJECUCION_DE_ORDEN_DE_ART`.`DATOS_DEL_VEHICULO` (
  `PE_UBICACION_DE_ORIGEN` VARCHAR(100) NOT NULL,
  `PE_DIRECCION_DE_ORIGEN` VARCHAR(100) NOT NULL,
  `PE_DIRECCIÓN_DE_ENTREGA` VARCHAR(200) NOT NULL,
  `TRANSPORTISTA` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`TRANSPORTISTA`),
  CONSTRAINT `fk_DATOS_DEL_VEHICULO_Transportista1`
    FOREIGN KEY (`TRANSPORTISTA`)
    REFERENCES `EJECUCION_DE_ORDEN_DE_ART`.`Transportista` (`PE_SERIE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EJECUCION_DE_ORDEN_DE_ART`.`DATOS_DE_TRASLADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EJECUCION_DE_ORDEN_DE_ART`.`DATOS_DE_TRASLADO` (
  `PE_FECHA_INICIO_DEL_TRASLADO` DATETIME NOT NULL,
  `PE_MODALIDAD_DE_TRASLADO` VARCHAR(45) NOT NULL,
  `PE_MOTIVOS_DE_TRASLADO` VARCHAR(20) NOT NULL,
  `PE_UBIGEO_PUNTO_PARTIDA` VARCHAR(105) NOT NULL,
  `PE_UBIGEO_PUNTO_LLEGADA` VARCHAR(105) NOT NULL,
  `ID` INT NOT NULL AUTO_INCREMENT,
  `PE_SERIE` VARCHAR(10) NOT NULL,
  INDEX `fk_DATOS_DE_TRASLADO_datos_de_la_guia1_idx` (`PE_SERIE` ASC) VISIBLE,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_DATOS_DE_TRASLADO_datos_de_la_guia1`
    FOREIGN KEY (`PE_SERIE`)
    REFERENCES `EJECUCION_DE_ORDEN_DE_ART`.`datos_de_la_guia` (`PE_SERIE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EJECUCION_DE_ORDEN_DE_ART`.`info_principal_has_datos_de_la_guia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EJECUCION_DE_ORDEN_DE_ART`.`info_principal_has_datos_de_la_guia` (
  `info_principal_PE_UBICACION_PARA_SERIE` VARCHAR(45) NOT NULL,
  `datos_de_la_guia_PE_SERIE` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`info_principal_PE_UBICACION_PARA_SERIE`, `datos_de_la_guia_PE_SERIE`),
  INDEX `fk_info_principal_has_datos_de_la_guia_datos_de_la_guia1_idx` (`datos_de_la_guia_PE_SERIE` ASC) VISIBLE,
  INDEX `fk_info_principal_has_datos_de_la_guia_info_principal1_idx` (`info_principal_PE_UBICACION_PARA_SERIE` ASC) VISIBLE,
  CONSTRAINT `fk_info_principal_has_datos_de_la_guia_info_principal1`
    FOREIGN KEY (`info_principal_PE_UBICACION_PARA_SERIE`)
    REFERENCES `EJECUCION_DE_ORDEN_DE_ART`.`info_principal` (`PE_UBICACION_PARA_SERIE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_info_principal_has_datos_de_la_guia_datos_de_la_guia1`
    FOREIGN KEY (`datos_de_la_guia_PE_SERIE`)
    REFERENCES `EJECUCION_DE_ORDEN_DE_ART`.`datos_de_la_guia` (`PE_SERIE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
